<!-- $Id: main.inc,v 2.1 2013 Exp $ -->

<!-- Main Content --> 


    <td class="main" valign="top"><br />
        <br />
       
       <div align="center"><h3>Welcome to 
        <b>@@system:name@@</b></h3></div>
        
                     
        <table align="center">
          <tr>
          <td align="center">Today's Statistics<br /><br />
          
    <table class="main_stats">
      <tr>
        <td class="main_stats">Up Time</td><td class="main_stats_bold">@@uptime@@</td>
        <td class="main_stats">Logons</td><td class="main_stats_bold">@@logons_today@@</td>
        <td class="main_stats">Posts</td><td class="main_stats_bold">@@posted_today@@</td>
        <td class="main_stats">Uploads</td><td class="main_stats_bold">@@uploaded_today@@</td>
      </tr>
      <tr>
        <td class="main_stats">Time On</td><td class="main_stats_bold">@@timeon_today@@ minutes</td>
        <td class="main_stats">New Users</td><td class="main_stats_bold">@@new_users_today@@</td>
        <td class="main_stats">Emails</td><td class="main_stats_bold">@@email_sent_today@@</td>
        <td class="main_stats">Downloads</td><td class="main_stats_bold">@@downloaded_today@@</td>
      </tr>
    </table>
    <br />
    </td>
    </tr>
    <tr>
    <td align="center">System Totals<br /><br />
    <table class="main_stats">
      <tr>
        <td class="main_stats">Time On</td><td class="main_stats_bold">@@total_timeon@@ minutes</td>
        <td class="main_stats">Logons</td><td class="main_stats_bold">@@total_logons@@</td>
        <td class="main_stats">Messages</td><td class="main_stats_bold">@@total_messages@@</td>
      </tr>
      <tr>
        <td class="main_stats">Users</td><td class="main_stats_bold">@@total_users@@</td>
        <td class="main_stats">Emails</td><td class="main_stats_bold">@@total_email@@</td>
        <td class="main_stats">Files</td><td class="main_stats_bold">@@total_files@@</td>
      </tr>
    </table>
    <br />
    </td>
    </tr>
    <tr>
    <td align="center"><strong>This system is UNDER CONSTRUCTION. <br><br>Please do not try to add yourself as a new user using the default menu on the left. It is not yet 
	configured properly. <br><br>At this time New User (test) accounts are available from MRDF in Darkmatter IRC in the #dev room.
	<br><br>The DarkMatter IRC is now active. Please click [irc] below to connect 
	and chat. <br><br>(Some Service Options listed below are disabled at this time and may or may not be implemented in the future.)</strong><br><br />@@additional_services@@</td>
    </tr>
    </table>
    <br /><br />

<!-- end Main Content -->

